### PR TITLE
Fixed SuperSpeed, KBInput, and added unlimited battery for the rescue hook and norg gun

### PR DESCRIPTION
**Pull request by Civilux**
If you check with unity explorer, the default value of movementForce is actually 17 instead of 10, and the default value of sprintMultiplier is 2.3 instead of 2

### CODE REVIEW

**Comment by TheGreenBandit** [comment]
image

**Comment by TheGreenBandit** [comment]
It is 10; sprint is 2. Where are you getting your values from?

**Comment by Civilux** [comment]
As I mentioned, unity explorer, I know dnspy says 10, but if you actually test the speeds in-game, you can tell you're slower with 10

**Comment by Toaaa** [comment]
> As I mentioned, unity explorer, I know dnspy says 10, but if you actually test the speeds in-game, you can tell you're slower with 10

The "real" value is 16f. I already fixed SuperSpeed in https://github.com/IcyRelic/SpookSuite/commit/914e153adacc2ef22338f442589badef94721080 but @TheGreenBandit reverted it for some reason.

**Comment by Civilux** [comment]
Yeah, it doesn't matter if it's 16 or 17; the difference won't be as noticeable. Just 10 is definitely too slow

**Comment by Toaaa** [comment]
> Yeah, it doesn't matter if it's 16 or 17; the difference won't be as noticeable. Just 10 is definitely too slow

It's 16f. But why did you change sprint from 2 to 2.3?

**Comment by TheGreenBandit** [comment]
> Yeah, it doesn't matter if it's 16 or 17; the difference won't be as noticeable. Just 10 is definitely too slow

It is 17, just logged it, idk if they set it on awake or something to 17 but i was just going off dnspy lol

**Comment by Civilux** [comment]
> > Yeah, it doesn't matter if it's 16 or 17; the difference won't be as noticeable. Just 10 is definitely too slow
> 
> It's 17f. But why did you change sprint from 2 to 2.3?

Same story, I checked with unity explorer

**Pull request merged**
